name: Build docker image

on:
  push:
    branches: ["main", "docker"]

env:
  cache_base: ghcr.io/na-trium-144/dotfiles/cache
  user: kou


jobs:
  build:
    strategy:
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            arch_img: archlinux
          - arch: arm64
            arch_img: lopsided/archlinux-arm64v8

    runs-on: ubuntu-22.04
    name: Build
    steps:
      - uses: actions/checkout@v4

      # https://stackoverflow.com/questions/58033366/how-to-get-the-current-branch-within-github-actions
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ vars.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push base_ubuntu22
        uses: docker/build-push-action@v6
        with:
          context: docker
          build-args: |
            BASE_USER=${{ env.user }}
            ARCH_IMG=${{ matrix.arch_img }}
            CHEZMOI_BRANCH=${{ steps.extract_branch.outputs.branch }}
          platforms: linux/${{ matrix.arch }}
          push: true
          cache-to: type=registry,ref=${{ env.cache_base }}:${{ matrix.arch }},mode=max
          target: base_ubuntu22
          tags: |
            ghcr.io/na-trium-144/dotfiles/base_ubuntu22:${{ matrix.arch }}
      - name: Build and push base_arch
        uses: docker/build-push-action@v6
        with:
          context: docker
          build-args: |
            BASE_USER=${{ env.user }}
            ARCH_IMG=${{ matrix.arch_img }}
            CHEZMOI_BRANCH=${{ steps.extract_branch.outputs.branch }}
          platforms: linux/${{ matrix.arch }}
          push: true
          cache-from: type=registry,ref=${{ env.cache_base }}:${{ matrix.arch }}
          target: base_arch
          tags: |
            ghcr.io/na-trium-144/dotfiles/base_arch:${{ matrix.arch }}
      - name: Build and push base_brew
        if: matrix.arch == 'amd64'
        uses: docker/build-push-action@v6
        with:
          context: docker
          build-args: |
            BASE_USER=${{ env.user }}
            ARCH_IMG=${{ matrix.arch_img }}
            CHEZMOI_BRANCH=${{ steps.extract_branch.outputs.branch }}
          platforms: linux/${{ matrix.arch }}
          push: true
          cache-from: type=registry,ref=${{ env.cache_base }}:${{ matrix.arch }}
          target: base_brew
          tags: |
            ghcr.io/na-trium-144/dotfiles/base_brew:${{ matrix.arch }}
      - name: Build and push base_nix
        uses: docker/build-push-action@v6
        with:
          context: docker
          build-args: |
            BASE_USER=${{ env.user }}
            ARCH_IMG=${{ matrix.arch_img }}
            CHEZMOI_BRANCH=${{ steps.extract_branch.outputs.branch }}
          platforms: linux/${{ matrix.arch }}
          push: true
          cache-from: type=registry,ref=${{ env.cache_base }}:${{ matrix.arch }}
          target: base_nix
          tags: |
            ghcr.io/na-trium-144/dotfiles/base_nix:${{ matrix.arch }}
